/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package card;

/**
 *
 * @author Nobilis
 */
public abstract class PupilCard_Layout extends javax.swing.JFrame {
    
    public PupilCard_Layout() {
        initComponents();
    }
    
    protected abstract String[] setSchools();
    
    protected abstract String[] setSchoolNumbers();
    
    protected abstract String[] setSchoolClasses();
    
    protected abstract String[] setClassLetters();
    
    protected abstract String[] setGender();
    
    protected abstract String[] setBornYears();
    
    protected abstract String[] setEnrolmentYears();
    
    protected abstract String[] setBornMonths();
    
    protected abstract String[] setEnrolmentMonths();
    
    protected abstract String[] setBornDates();
    
    protected abstract String[] setEnrolmentDates();
    
    protected abstract String[] setProgram();
    
    protected abstract String[] setClasses();
    
    protected abstract String[] setHours();
    
    protected abstract String[] setWeek();
    
    protected abstract javax.swing.table.DefaultTableModel setAchievmentTable();
    
    protected abstract void setTableSettings();
    
    protected abstract String[][] getTableContent();
    
    protected abstract void Ok();
    
    protected abstract void cancel();
    
    protected abstract void setDocumentsItem (int item);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Panel = new javax.swing.JPanel();
        Panel_Tabs = new javax.swing.JTabbedPane();
        Panel_Pupil = new javax.swing.JPanel();
        panel_Pupil_Left = new javax.swing.JPanel();
        label_Last_Name = new javax.swing.JLabel();
        field_Last_Name = new javax.swing.JTextField();
        label_First_Name = new javax.swing.JLabel();
        field_First_Name = new javax.swing.JTextField();
        label_Patronymic_Name = new javax.swing.JLabel();
        field_Patronymic_Name = new javax.swing.JTextField();
        label_Specialty = new javax.swing.JLabel();
        field_Speciality = new javax.swing.JTextField();
        label_Instrument = new javax.swing.JLabel();
        field_Instrument = new javax.swing.JTextField();
        label_School = new javax.swing.JLabel();
        box_School = new javax.swing.JComboBox<String>();
        label_School_Number = new javax.swing.JLabel();
        box_School_Number = new javax.swing.JComboBox<String>();
        label_School_Class = new javax.swing.JLabel();
        box_School_Class = new javax.swing.JComboBox<String>();
        box_School_Class_Letter = new javax.swing.JComboBox<String>();
        panel_Pupil_Right = new javax.swing.JPanel();
        label_Gender = new javax.swing.JLabel();
        box_Gender = new javax.swing.JComboBox<String>();
        label_Date_Born = new javax.swing.JLabel();
        box_Year_Born = new javax.swing.JComboBox<String>();
        box_Month_Born = new javax.swing.JComboBox<String>();
        box_Date_Born = new javax.swing.JComboBox<String>();
        label_Date_Enrolment = new javax.swing.JLabel();
        box_Year_Enrolment = new javax.swing.JComboBox<String>();
        box_Month_Enrolment = new javax.swing.JComboBox<String>();
        box_Date_Enrolment = new javax.swing.JComboBox<String>();
        label_Phone = new javax.swing.JLabel();
        field_Phone = new javax.swing.JTextField();
        label_Adress = new javax.swing.JLabel();
        scroll_Pane_Adress = new javax.swing.JScrollPane();
        area_Adress = new javax.swing.JTextArea();
        Panel_Parents = new javax.swing.JPanel();
        panel_Mother = new javax.swing.JPanel();
        label_Mother_Last_Name = new javax.swing.JLabel();
        field_Mother_Last_Name = new javax.swing.JTextField();
        label_Mother_First_Name = new javax.swing.JLabel();
        field_Mother_First_Name = new javax.swing.JTextField();
        label_Mother_Patronymic_Name = new javax.swing.JLabel();
        field_Mother_Patronymic = new javax.swing.JTextField();
        label_Mother_Phone = new javax.swing.JLabel();
        field_Mother_Phone = new javax.swing.JTextField();
        label_Mother_Work = new javax.swing.JLabel();
        scroll_Pane_Mother_Work = new javax.swing.JScrollPane();
        area_Mother_Work = new javax.swing.JTextArea();
        label_Mother_Post = new javax.swing.JLabel();
        field_Mother_Post = new javax.swing.JTextField();
        panel_Father = new javax.swing.JPanel();
        label_Father_Last_Name = new javax.swing.JLabel();
        field_Father_Last_Name = new javax.swing.JTextField();
        label_Father_First_Name = new javax.swing.JLabel();
        field_Father_First_Name = new javax.swing.JTextField();
        label_Father_Patronymic_Name = new javax.swing.JLabel();
        field_Father_Patronymic = new javax.swing.JTextField();
        label_Father_Phone = new javax.swing.JLabel();
        field_Father_Phone = new javax.swing.JTextField();
        label_Father_Work = new javax.swing.JLabel();
        scroll_Pane_Father_Work = new javax.swing.JScrollPane();
        area_Father_Work = new javax.swing.JTextArea();
        label_Father_Post = new javax.swing.JLabel();
        field_Father_Post = new javax.swing.JTextField();
        Panel_Documents = new javax.swing.JPanel();
        panel_Doc_Child = new javax.swing.JPanel();
        box_Statement = new javax.swing.JCheckBox();
        box_Contract = new javax.swing.JCheckBox();
        box_Birth_Certificate = new javax.swing.JCheckBox();
        box_Medical_Certificate = new javax.swing.JCheckBox();
        box_Child_SNILS = new javax.swing.JCheckBox();
        box_Photo = new javax.swing.JCheckBox();
        panel_Doc_Mother = new javax.swing.JPanel();
        box_Mother_Passport = new javax.swing.JCheckBox();
        box_Mother_SNILS = new javax.swing.JCheckBox();
        box_Mother_Consent = new javax.swing.JCheckBox();
        panel_Doc_Father = new javax.swing.JPanel();
        box_Father_Passport = new javax.swing.JCheckBox();
        box_Father_SNILS = new javax.swing.JCheckBox();
        box_Father_Consent = new javax.swing.JCheckBox();
        Panel_Learning = new javax.swing.JPanel();
        panel_Program = new javax.swing.JPanel();
        label_Program = new javax.swing.JLabel();
        box_Program = new javax.swing.JComboBox<String>();
        label_Klass = new javax.swing.JLabel();
        box_Class = new javax.swing.JComboBox<String>();
        label_Hours = new javax.swing.JLabel();
        box_Hours = new javax.swing.JComboBox<String>();
        label_Schedule = new javax.swing.JLabel();
        box_First = new javax.swing.JComboBox<String>();
        box_Second = new javax.swing.JComboBox<String>();
        box_Third = new javax.swing.JComboBox<String>();
        panel_Teaching = new javax.swing.JPanel();
        label_Spec_Teacher = new javax.swing.JLabel();
        field_Spec_Teacher = new javax.swing.JTextField();
        label_Theor_Teacher = new javax.swing.JLabel();
        field_Theor_Teacher = new javax.swing.JTextField();
        label_Choir_Teacher = new javax.swing.JLabel();
        field_Choir_Teacher = new javax.swing.JTextField();
        label_Piano_Teacher = new javax.swing.JLabel();
        field_Piano_Teacher = new javax.swing.JTextField();
        label_Ensemble_Teacher = new javax.swing.JLabel();
        field_Ensemble_Teacher = new javax.swing.JTextField();
        Panel_Repertoire = new javax.swing.JPanel();
        panel_1_Semester = new javax.swing.JPanel();
        label_1_Semester = new javax.swing.JLabel();
        scroll_Pane_1_Semester = new javax.swing.JScrollPane();
        area_1_Semester = new javax.swing.JTextArea();
        panel_2_Semester = new javax.swing.JPanel();
        scroll_Pane_2_Semester = new javax.swing.JScrollPane();
        area_2_Semester = new javax.swing.JTextArea();
        label_2_Semester = new javax.swing.JLabel();
        Panel_Notes = new javax.swing.JPanel();
        panel_Notes2 = new javax.swing.JPanel();
        scroll_Pane_Notes = new javax.swing.JScrollPane();
        area_Notes = new javax.swing.JTextArea();
        Panel_Achievment = new javax.swing.JPanel();
        scroll_Pane_Achievment = new javax.swing.JScrollPane();
        table_Achievment = new javax.swing.JTable();
        Panel_Bottom = new javax.swing.JPanel();
        button_OK = new javax.swing.JButton();
        button_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Tabs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel_Tabs.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        panel_Pupil_Left.setPreferredSize(new java.awt.Dimension(386, 506));

        label_Last_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Last_Name.setText("Фамилия");

        field_Last_Name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_First_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_First_Name.setText("Имя");

        field_First_Name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Patronymic_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Patronymic_Name.setText("Отчество");

        field_Patronymic_Name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Specialty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Specialty.setText("Специальность");

        field_Speciality.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Instrument.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Instrument.setText("Инструмент");

        field_Instrument.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_School.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_School.setText("Школа/детский сад");

        box_School.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_School.setModel(new javax.swing.DefaultComboBoxModel<>(setSchools()));

        label_School_Number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_School_Number.setText("№");

        box_School_Number.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_School_Number.setModel(new javax.swing.DefaultComboBoxModel<>(setSchoolNumbers()));

        label_School_Class.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_School_Class.setText("Класс");

        box_School_Class.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_School_Class.setModel(new javax.swing.DefaultComboBoxModel<>(setSchoolClasses()));

        box_School_Class_Letter.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_School_Class_Letter.setModel(new javax.swing.DefaultComboBoxModel<>(setClassLetters()));

        javax.swing.GroupLayout panel_Pupil_LeftLayout = new javax.swing.GroupLayout(panel_Pupil_Left);
        panel_Pupil_Left.setLayout(panel_Pupil_LeftLayout);
        panel_Pupil_LeftLayout.setHorizontalGroup(
            panel_Pupil_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Pupil_LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Pupil_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_Pupil_LeftLayout.createSequentialGroup()
                        .addComponent(label_School_Number)
                        .addGap(18, 18, 18)
                        .addComponent(box_School_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(label_School_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(box_School_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(box_School_Class_Letter, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_Pupil_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_Pupil_LeftLayout.createSequentialGroup()
                            .addComponent(label_School)
                            .addGap(38, 38, 38)
                            .addComponent(box_School, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(field_First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_Patronymic_Name)
                        .addComponent(label_Specialty)
                        .addComponent(field_Speciality, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_Instrument)
                        .addComponent(label_Last_Name)
                        .addComponent(field_Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_First_Name)
                        .addComponent(field_Patronymic_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(field_Instrument, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_Pupil_LeftLayout.setVerticalGroup(
            panel_Pupil_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Pupil_LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Last_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_First_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_Patronymic_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Patronymic_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_Specialty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Speciality, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_Instrument)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Instrument, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_Pupil_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box_School, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_School))
                .addGap(18, 18, 18)
                .addGroup(panel_Pupil_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box_School_Class_Letter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_School_Class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_School_Class)
                    .addComponent(label_School_Number)
                    .addComponent(box_School_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label_Gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Gender.setText("Пол");

        box_Gender.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(setGender()));

        label_Date_Born.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Date_Born.setText("Дата рождения");

        box_Year_Born.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_Year_Born.setModel(new javax.swing.DefaultComboBoxModel<>(setBornYears()));
        box_Year_Born.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Year_BornActionPerformed(evt);
            }
        });

        box_Month_Born.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_Month_Born.setModel(new javax.swing.DefaultComboBoxModel<>(setBornMonths()));

        box_Date_Born.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_Date_Born.setModel(new javax.swing.DefaultComboBoxModel<>(setBornDates()));

        label_Date_Enrolment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Date_Enrolment.setText("Дата поступления");

        box_Year_Enrolment.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_Year_Enrolment.setModel(new javax.swing.DefaultComboBoxModel<>(setEnrolmentYears()));
        box_Year_Enrolment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Year_EnrolmentActionPerformed(evt);
            }
        });

        box_Month_Enrolment.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_Month_Enrolment.setModel(new javax.swing.DefaultComboBoxModel<>(setEnrolmentMonths()));

        box_Date_Enrolment.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_Date_Enrolment.setModel(new javax.swing.DefaultComboBoxModel<>(setEnrolmentDates()));

        label_Phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Phone.setText("Телефон");

        field_Phone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Adress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Adress.setText("Адрес");

        area_Adress.setColumns(20);
        area_Adress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        area_Adress.setRows(5);
        area_Adress.setToolTipText("");
        area_Adress.setPreferredSize(new java.awt.Dimension(342, 149));
        scroll_Pane_Adress.setViewportView(area_Adress);

        javax.swing.GroupLayout panel_Pupil_RightLayout = new javax.swing.GroupLayout(panel_Pupil_Right);
        panel_Pupil_Right.setLayout(panel_Pupil_RightLayout);
        panel_Pupil_RightLayout.setHorizontalGroup(
            panel_Pupil_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Pupil_RightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Pupil_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_Pupil_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(scroll_Pane_Adress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_Pupil_RightLayout.createSequentialGroup()
                            .addGroup(panel_Pupil_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_Pupil_RightLayout.createSequentialGroup()
                                    .addComponent(label_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(field_Phone))
                                .addGroup(panel_Pupil_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel_Pupil_RightLayout.createSequentialGroup()
                                        .addComponent(box_Date_Born, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(box_Month_Born, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(box_Year_Born, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_Pupil_RightLayout.createSequentialGroup()
                                        .addComponent(box_Date_Enrolment, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(box_Month_Enrolment, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(box_Year_Enrolment, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(104, 104, 104)))
                    .addGroup(panel_Pupil_RightLayout.createSequentialGroup()
                        .addGroup(panel_Pupil_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_Date_Born, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_Date_Enrolment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_Adress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        panel_Pupil_RightLayout.setVerticalGroup(
            panel_Pupil_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Pupil_RightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Gender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_Date_Born)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_Pupil_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box_Date_Born, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_Year_Born, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_Month_Born, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_Date_Enrolment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_Pupil_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box_Date_Enrolment, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_Year_Enrolment, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_Month_Enrolment, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panel_Pupil_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Phone))
                .addGap(18, 18, 18)
                .addComponent(label_Adress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_Pane_Adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_PupilLayout = new javax.swing.GroupLayout(Panel_Pupil);
        Panel_Pupil.setLayout(Panel_PupilLayout);
        Panel_PupilLayout.setHorizontalGroup(
            Panel_PupilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PupilLayout.createSequentialGroup()
                .addComponent(panel_Pupil_Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_Pupil_Right, javax.swing.GroupLayout.PREFERRED_SIZE, 352, Short.MAX_VALUE))
        );
        Panel_PupilLayout.setVerticalGroup(
            Panel_PupilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Pupil_Right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_PupilLayout.createSequentialGroup()
                .addComponent(panel_Pupil_Left, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Panel_Tabs.addTab("Ученик", Panel_Pupil);

        panel_Mother.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Мать", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        panel_Mother.setPreferredSize(new java.awt.Dimension(358, 100));

        label_Mother_Last_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Mother_Last_Name.setText("Фамилия");

        field_Mother_Last_Name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Mother_First_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Mother_First_Name.setText("Имя");

        field_Mother_First_Name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Mother_Patronymic_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Mother_Patronymic_Name.setText("Отчество");

        field_Mother_Patronymic.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Mother_Phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Mother_Phone.setText("Телефон");

        field_Mother_Phone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Mother_Work.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Mother_Work.setText("Место работы");

        area_Mother_Work.setColumns(20);
        area_Mother_Work.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        area_Mother_Work.setRows(5);
        scroll_Pane_Mother_Work.setViewportView(area_Mother_Work);

        label_Mother_Post.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Mother_Post.setText("Должность");

        field_Mother_Post.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout panel_MotherLayout = new javax.swing.GroupLayout(panel_Mother);
        panel_Mother.setLayout(panel_MotherLayout);
        panel_MotherLayout.setHorizontalGroup(
            panel_MotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_MotherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_MotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_Pane_Mother_Work, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(field_Mother_Last_Name)
                    .addComponent(field_Mother_First_Name)
                    .addComponent(field_Mother_Patronymic)
                    .addGroup(panel_MotherLayout.createSequentialGroup()
                        .addComponent(label_Mother_Phone)
                        .addGap(18, 18, 18)
                        .addComponent(field_Mother_Phone, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                    .addComponent(field_Mother_Post)
                    .addGroup(panel_MotherLayout.createSequentialGroup()
                        .addGroup(panel_MotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Mother_Patronymic_Name)
                            .addComponent(label_Mother_Last_Name)
                            .addComponent(label_Mother_First_Name)
                            .addComponent(label_Mother_Work)
                            .addComponent(label_Mother_Post))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_MotherLayout.setVerticalGroup(
            panel_MotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_MotherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Mother_Last_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Mother_Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Mother_First_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Mother_First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Mother_Patronymic_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Mother_Patronymic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_MotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_Mother_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Mother_Phone))
                .addGap(18, 18, 18)
                .addComponent(label_Mother_Work)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll_Pane_Mother_Work, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_Mother_Post)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Mother_Post, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_Father.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Отец", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        panel_Father.setPreferredSize(new java.awt.Dimension(358, 0));

        label_Father_Last_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Father_Last_Name.setText("Фамилия");

        field_Father_Last_Name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Father_First_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Father_First_Name.setText("Имя");

        field_Father_First_Name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Father_Patronymic_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Father_Patronymic_Name.setText("Отчество");

        field_Father_Patronymic.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Father_Phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Father_Phone.setText("Телефон");

        field_Father_Phone.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Father_Work.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Father_Work.setText("Место работы");

        area_Father_Work.setColumns(20);
        area_Father_Work.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        area_Father_Work.setRows(5);
        scroll_Pane_Father_Work.setViewportView(area_Father_Work);

        label_Father_Post.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Father_Post.setText("Должность");

        field_Father_Post.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout panel_FatherLayout = new javax.swing.GroupLayout(panel_Father);
        panel_Father.setLayout(panel_FatherLayout);
        panel_FatherLayout.setHorizontalGroup(
            panel_FatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FatherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_FatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_FatherLayout.createSequentialGroup()
                        .addGroup(panel_FatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Father_Last_Name)
                            .addComponent(label_Father_First_Name))
                        .addGap(291, 291, 291))
                    .addGroup(panel_FatherLayout.createSequentialGroup()
                        .addGroup(panel_FatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_FatherLayout.createSequentialGroup()
                                .addGroup(panel_FatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_Father_Patronymic_Name)
                                    .addComponent(label_Father_Work)
                                    .addComponent(label_Father_Post))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(field_Father_Last_Name)
                            .addComponent(field_Father_First_Name)
                            .addComponent(field_Father_Patronymic)
                            .addGroup(panel_FatherLayout.createSequentialGroup()
                                .addComponent(label_Father_Phone)
                                .addGap(18, 18, 18)
                                .addComponent(field_Father_Phone))
                            .addComponent(scroll_Pane_Father_Work, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(field_Father_Post))
                        .addContainerGap())))
        );
        panel_FatherLayout.setVerticalGroup(
            panel_FatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FatherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Father_Last_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Father_Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Father_First_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Father_First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Father_Patronymic_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Father_Patronymic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_FatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_Father_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Father_Phone))
                .addGap(18, 18, 18)
                .addComponent(label_Father_Work)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll_Pane_Father_Work, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_Father_Post)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Father_Post, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Panel_ParentsLayout = new javax.swing.GroupLayout(Panel_Parents);
        Panel_Parents.setLayout(Panel_ParentsLayout);
        Panel_ParentsLayout.setHorizontalGroup(
            Panel_ParentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ParentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Mother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Father, javax.swing.GroupLayout.PREFERRED_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_ParentsLayout.setVerticalGroup(
            Panel_ParentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Mother, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
            .addComponent(panel_Father, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        Panel_Tabs.addTab("Родители", Panel_Parents);

        panel_Doc_Child.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Ученик", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        box_Statement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        box_Statement.setText("Заявление");
        box_Statement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Statement_ActionPerformed(evt);
            }
        });

        box_Contract.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        box_Contract.setText("Договор");
        box_Contract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Contract_ActionPerformed(evt);
            }
        });

        box_Birth_Certificate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        box_Birth_Certificate.setText("Свидетельство о рождении / паспорт");
        box_Birth_Certificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Birth_Certificate_ActionPerformed(evt);
            }
        });

        box_Medical_Certificate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        box_Medical_Certificate.setText("Медицинская справка");
        box_Medical_Certificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Medical_Certificate_ActionPerformed(evt);
            }
        });

        box_Child_SNILS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        box_Child_SNILS.setText("СНИЛС");
        box_Child_SNILS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Child_SNILS_ActionPerformed(evt);
            }
        });

        box_Photo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        box_Photo.setText("Фотографии");
        box_Photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Photo_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Doc_ChildLayout = new javax.swing.GroupLayout(panel_Doc_Child);
        panel_Doc_Child.setLayout(panel_Doc_ChildLayout);
        panel_Doc_ChildLayout.setHorizontalGroup(
            panel_Doc_ChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Doc_ChildLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Doc_ChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(box_Birth_Certificate, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_Statement, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_Contract, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_Doc_ChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(box_Photo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_Child_SNILS, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_Medical_Certificate))
                .addGap(22, 22, 22))
        );
        panel_Doc_ChildLayout.setVerticalGroup(
            panel_Doc_ChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Doc_ChildLayout.createSequentialGroup()
                .addGroup(panel_Doc_ChildLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_Doc_ChildLayout.createSequentialGroup()
                        .addComponent(box_Medical_Certificate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(box_Child_SNILS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box_Photo)
                        .addGap(3, 3, 3))
                    .addGroup(panel_Doc_ChildLayout.createSequentialGroup()
                        .addComponent(box_Statement)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(box_Contract)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(box_Birth_Certificate)))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        panel_Doc_Mother.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Мать", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_Doc_Mother.setPreferredSize(new java.awt.Dimension(334, 243));

        box_Mother_Passport.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        box_Mother_Passport.setText("Паспорт");
        box_Mother_Passport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Mother_Passport_ActionPerformed(evt);
            }
        });

        box_Mother_SNILS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        box_Mother_SNILS.setText("СНИЛС");
        box_Mother_SNILS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Mother_SNILS_ActionPerformed(evt);
            }
        });

        box_Mother_Consent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        box_Mother_Consent.setText("Согласие на обраоботку п/данных");
        box_Mother_Consent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Mother_Consent_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Doc_MotherLayout = new javax.swing.GroupLayout(panel_Doc_Mother);
        panel_Doc_Mother.setLayout(panel_Doc_MotherLayout);
        panel_Doc_MotherLayout.setHorizontalGroup(
            panel_Doc_MotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Doc_MotherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Doc_MotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(box_Mother_Consent, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_Doc_MotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(box_Mother_Passport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(box_Mother_SNILS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panel_Doc_MotherLayout.setVerticalGroup(
            panel_Doc_MotherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Doc_MotherLayout.createSequentialGroup()
                .addComponent(box_Mother_Passport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(box_Mother_SNILS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(box_Mother_Consent)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        panel_Doc_Father.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Отец", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_Doc_Father.setPreferredSize(new java.awt.Dimension(327, 24));

        box_Father_Passport.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        box_Father_Passport.setText("Паспорт");
        box_Father_Passport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Father_Passport_ActionPerformed(evt);
            }
        });

        box_Father_SNILS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        box_Father_SNILS.setText("СНИЛС");
        box_Father_SNILS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Father_SNILS_ActionPerformed(evt);
            }
        });

        box_Father_Consent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        box_Father_Consent.setText("Согласие на обраоботку п/данных");
        box_Father_Consent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Father_Consent_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Doc_FatherLayout = new javax.swing.GroupLayout(panel_Doc_Father);
        panel_Doc_Father.setLayout(panel_Doc_FatherLayout);
        panel_Doc_FatherLayout.setHorizontalGroup(
            panel_Doc_FatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Doc_FatherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Doc_FatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(box_Father_Consent, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_Doc_FatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(box_Father_SNILS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(box_Father_Passport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panel_Doc_FatherLayout.setVerticalGroup(
            panel_Doc_FatherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Doc_FatherLayout.createSequentialGroup()
                .addComponent(box_Father_Passport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(box_Father_SNILS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(box_Father_Consent)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_DocumentsLayout = new javax.swing.GroupLayout(Panel_Documents);
        Panel_Documents.setLayout(Panel_DocumentsLayout);
        Panel_DocumentsLayout.setHorizontalGroup(
            Panel_DocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_DocumentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_DocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_Doc_Child, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_DocumentsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panel_Doc_Mother, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_Doc_Father, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        Panel_DocumentsLayout.setVerticalGroup(
            Panel_DocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_DocumentsLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(panel_Doc_Child, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_DocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_Doc_Mother, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(panel_Doc_Father, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        Panel_Tabs.addTab("Документы", Panel_Documents);

        label_Program.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Program.setText("Программа");

        box_Program.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_Program.setModel(new javax.swing.DefaultComboBoxModel<>(setProgram()));
        box_Program.setToolTipText("");

        label_Klass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Klass.setText("Класс");

        box_Class.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_Class.setModel(new javax.swing.DefaultComboBoxModel<>(setClasses()));

        label_Hours.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Hours.setText("Часы");

        box_Hours.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_Hours.setModel(new javax.swing.DefaultComboBoxModel<>(setHours()));

        label_Schedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Schedule.setText("Расписание");

        box_First.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_First.setModel(new javax.swing.DefaultComboBoxModel<>(setWeek()));
        box_First.setToolTipText("");

        box_Second.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_Second.setModel(new javax.swing.DefaultComboBoxModel<>(setWeek()));
        box_Second.setToolTipText("");

        box_Third.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        box_Third.setModel(new javax.swing.DefaultComboBoxModel<>(setWeek()));
        box_Third.setToolTipText("");

        javax.swing.GroupLayout panel_ProgramLayout = new javax.swing.GroupLayout(panel_Program);
        panel_Program.setLayout(panel_ProgramLayout);
        panel_ProgramLayout.setHorizontalGroup(
            panel_ProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ProgramLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Schedule)
                    .addGroup(panel_ProgramLayout.createSequentialGroup()
                        .addGroup(panel_ProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(box_Second, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_ProgramLayout.createSequentialGroup()
                                .addGroup(panel_ProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box_Program, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_Program))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel_ProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_Klass)))
                            .addComponent(box_First, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(box_Third, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_ProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Hours)
                            .addComponent(box_Hours, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_ProgramLayout.setVerticalGroup(
            panel_ProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ProgramLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Program)
                    .addComponent(label_Klass)
                    .addComponent(label_Hours))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(box_Hours, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(box_Class)
                    .addComponent(box_Program))
                .addGap(18, 18, 18)
                .addComponent(label_Schedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box_First, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(box_Second, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(box_Third, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label_Spec_Teacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Spec_Teacher.setText("Преподаватель специальности");

        field_Spec_Teacher.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Theor_Teacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Theor_Teacher.setText("Преподаватель теор. дисциплин");

        field_Theor_Teacher.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Choir_Teacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Choir_Teacher.setText("Преподаватель хора");

        field_Choir_Teacher.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Piano_Teacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Piano_Teacher.setText("Преподаватель общего фортепиано");

        field_Piano_Teacher.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        label_Ensemble_Teacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_Ensemble_Teacher.setText("Преподаватель ансамбля/оркестра");

        field_Ensemble_Teacher.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout panel_TeachingLayout = new javax.swing.GroupLayout(panel_Teaching);
        panel_Teaching.setLayout(panel_TeachingLayout);
        panel_TeachingLayout.setHorizontalGroup(
            panel_TeachingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TeachingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_TeachingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_Spec_Teacher)
                    .addGroup(panel_TeachingLayout.createSequentialGroup()
                        .addComponent(label_Spec_Teacher)
                        .addContainerGap(216, Short.MAX_VALUE))
                    .addComponent(field_Theor_Teacher)
                    .addComponent(field_Choir_Teacher)
                    .addComponent(field_Ensemble_Teacher)
                    .addComponent(field_Piano_Teacher)
                    .addGroup(panel_TeachingLayout.createSequentialGroup()
                        .addGroup(panel_TeachingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Theor_Teacher)
                            .addComponent(label_Choir_Teacher)
                            .addComponent(label_Piano_Teacher)
                            .addComponent(label_Ensemble_Teacher))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panel_TeachingLayout.setVerticalGroup(
            panel_TeachingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TeachingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Spec_Teacher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Spec_Teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_Theor_Teacher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Theor_Teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_Choir_Teacher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Choir_Teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_Piano_Teacher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Piano_Teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_Ensemble_Teacher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Ensemble_Teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_LearningLayout = new javax.swing.GroupLayout(Panel_Learning);
        Panel_Learning.setLayout(Panel_LearningLayout);
        Panel_LearningLayout.setHorizontalGroup(
            Panel_LearningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LearningLayout.createSequentialGroup()
                .addComponent(panel_Program, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_Teaching, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_LearningLayout.setVerticalGroup(
            Panel_LearningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LearningLayout.createSequentialGroup()
                .addGroup(Panel_LearningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Teaching, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_Program, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        Panel_Tabs.addTab("Обучение", Panel_Learning);

        panel_1_Semester.setPreferredSize(new java.awt.Dimension(100, 244));

        label_1_Semester.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_1_Semester.setText("I полугодие");

        area_1_Semester.setColumns(20);
        area_1_Semester.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        area_1_Semester.setRows(5);
        scroll_Pane_1_Semester.setViewportView(area_1_Semester);

        javax.swing.GroupLayout panel_1_SemesterLayout = new javax.swing.GroupLayout(panel_1_Semester);
        panel_1_Semester.setLayout(panel_1_SemesterLayout);
        panel_1_SemesterLayout.setHorizontalGroup(
            panel_1_SemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1_SemesterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_1_SemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_1_SemesterLayout.createSequentialGroup()
                        .addComponent(label_1_Semester)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scroll_Pane_1_Semester))
                .addContainerGap())
        );
        panel_1_SemesterLayout.setVerticalGroup(
            panel_1_SemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1_SemesterLayout.createSequentialGroup()
                .addComponent(label_1_Semester)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_Pane_1_Semester, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_2_Semester.setPreferredSize(new java.awt.Dimension(100, 244));

        area_2_Semester.setColumns(20);
        area_2_Semester.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        area_2_Semester.setRows(5);
        scroll_Pane_2_Semester.setViewportView(area_2_Semester);

        javax.swing.GroupLayout panel_2_SemesterLayout = new javax.swing.GroupLayout(panel_2_Semester);
        panel_2_Semester.setLayout(panel_2_SemesterLayout);
        panel_2_SemesterLayout.setHorizontalGroup(
            panel_2_SemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_2_SemesterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_Pane_2_Semester, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_2_SemesterLayout.setVerticalGroup(
            panel_2_SemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll_Pane_2_Semester, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        label_2_Semester.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_2_Semester.setText("II полугодие");

        javax.swing.GroupLayout Panel_RepertoireLayout = new javax.swing.GroupLayout(Panel_Repertoire);
        Panel_Repertoire.setLayout(Panel_RepertoireLayout);
        Panel_RepertoireLayout.setHorizontalGroup(
            Panel_RepertoireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_1_Semester, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addComponent(panel_2_Semester, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(Panel_RepertoireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_2_Semester)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_RepertoireLayout.setVerticalGroup(
            Panel_RepertoireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RepertoireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_1_Semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label_2_Semester)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_2_Semester, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Panel_Tabs.addTab("Репертуар", Panel_Repertoire);

        area_Notes.setColumns(20);
        area_Notes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        area_Notes.setRows(5);
        scroll_Pane_Notes.setViewportView(area_Notes);

        javax.swing.GroupLayout panel_Notes2Layout = new javax.swing.GroupLayout(panel_Notes2);
        panel_Notes2.setLayout(panel_Notes2Layout);
        panel_Notes2Layout.setHorizontalGroup(
            panel_Notes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll_Pane_Notes, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        panel_Notes2Layout.setVerticalGroup(
            panel_Notes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll_Pane_Notes, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Panel_NotesLayout = new javax.swing.GroupLayout(Panel_Notes);
        Panel_Notes.setLayout(Panel_NotesLayout);
        Panel_NotesLayout.setHorizontalGroup(
            Panel_NotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Notes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Panel_NotesLayout.setVerticalGroup(
            Panel_NotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Notes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Panel_Tabs.addTab("Заметки", Panel_Notes);

        Panel_Achievment.setMinimumSize(new java.awt.Dimension(0, 0));

        table_Achievment.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        table_Achievment.setModel(setAchievmentTable());
        table_Achievment.setRowHeight(30);
        table_Achievment.getTableHeader().setReorderingAllowed(false);
        scroll_Pane_Achievment.setViewportView(table_Achievment);

        javax.swing.GroupLayout Panel_AchievmentLayout = new javax.swing.GroupLayout(Panel_Achievment);
        Panel_Achievment.setLayout(Panel_AchievmentLayout);
        Panel_AchievmentLayout.setHorizontalGroup(
            Panel_AchievmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AchievmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_Pane_Achievment)
                .addContainerGap())
        );
        Panel_AchievmentLayout.setVerticalGroup(
            Panel_AchievmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AchievmentLayout.createSequentialGroup()
                .addComponent(scroll_Pane_Achievment, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 307, Short.MAX_VALUE))
        );

        Panel_Tabs.addTab("Успеваемость", Panel_Achievment);

        button_OK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button_OK.setText("Ok");
        button_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_OK_ActionPerformed(evt);
            }
        });

        button_Cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button_Cancel.setText("Отмена");
        button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Cancel_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_BottomLayout = new javax.swing.GroupLayout(Panel_Bottom);
        Panel_Bottom.setLayout(Panel_BottomLayout);
        Panel_BottomLayout.setHorizontalGroup(
            Panel_BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_BottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        Panel_BottomLayout.setVerticalGroup(
            Panel_BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BottomLayout.createSequentialGroup()
                .addGroup(Panel_BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Main_PanelLayout = new javax.swing.GroupLayout(Main_Panel);
        Main_Panel.setLayout(Main_PanelLayout);
        Main_PanelLayout.setHorizontalGroup(
            Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main_PanelLayout.createSequentialGroup()
                        .addComponent(Panel_Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Panel_Bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Main_PanelLayout.setVerticalGroup(
            Main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box_Statement_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Statement_ActionPerformed
        setDocumentsItem(0);
    }//GEN-LAST:event_box_Statement_ActionPerformed

    private void box_Contract_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Contract_ActionPerformed
        setDocumentsItem(1);
    }//GEN-LAST:event_box_Contract_ActionPerformed

    private void box_Birth_Certificate_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Birth_Certificate_ActionPerformed
        setDocumentsItem(2);
    }//GEN-LAST:event_box_Birth_Certificate_ActionPerformed

    private void box_Medical_Certificate_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Medical_Certificate_ActionPerformed
        setDocumentsItem(3);
    }//GEN-LAST:event_box_Medical_Certificate_ActionPerformed

    private void box_Child_SNILS_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Child_SNILS_ActionPerformed
        setDocumentsItem(4);
    }//GEN-LAST:event_box_Child_SNILS_ActionPerformed

    private void box_Photo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Photo_ActionPerformed
        setDocumentsItem(5);
    }//GEN-LAST:event_box_Photo_ActionPerformed

    private void box_Mother_Passport_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Mother_Passport_ActionPerformed
        setDocumentsItem(6);
    }//GEN-LAST:event_box_Mother_Passport_ActionPerformed

    private void box_Mother_SNILS_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Mother_SNILS_ActionPerformed
        setDocumentsItem(7);
    }//GEN-LAST:event_box_Mother_SNILS_ActionPerformed

    private void box_Mother_Consent_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Mother_Consent_ActionPerformed
        setDocumentsItem(8);
    }//GEN-LAST:event_box_Mother_Consent_ActionPerformed

    private void box_Father_Passport_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Father_Passport_ActionPerformed
        setDocumentsItem(9);
    }//GEN-LAST:event_box_Father_Passport_ActionPerformed

    private void box_Father_SNILS_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Father_SNILS_ActionPerformed
        setDocumentsItem(10);
    }//GEN-LAST:event_box_Father_SNILS_ActionPerformed

    private void box_Father_Consent_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Father_Consent_ActionPerformed
        setDocumentsItem(11);
    }//GEN-LAST:event_box_Father_Consent_ActionPerformed

    private void button_OK_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_OK_ActionPerformed
        Ok();
    }//GEN-LAST:event_button_OK_ActionPerformed

    private void button_Cancel_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Cancel_ActionPerformed
        cancel();
    }//GEN-LAST:event_button_Cancel_ActionPerformed

    private void box_Year_BornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Year_BornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_Year_BornActionPerformed

    private void box_Year_EnrolmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Year_EnrolmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_Year_EnrolmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PupilCard_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PupilCard_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PupilCard_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PupilCard_Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new PupilCard_Layout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JPanel Panel_Achievment;
    private javax.swing.JPanel Panel_Bottom;
    private javax.swing.JPanel Panel_Documents;
    private javax.swing.JPanel Panel_Learning;
    private javax.swing.JPanel Panel_Notes;
    private javax.swing.JPanel Panel_Parents;
    private javax.swing.JPanel Panel_Pupil;
    private javax.swing.JPanel Panel_Repertoire;
    private javax.swing.JTabbedPane Panel_Tabs;
    protected javax.swing.JTextArea area_1_Semester;
    protected javax.swing.JTextArea area_2_Semester;
    protected javax.swing.JTextArea area_Adress;
    protected javax.swing.JTextArea area_Father_Work;
    protected javax.swing.JTextArea area_Mother_Work;
    protected javax.swing.JTextArea area_Notes;
    protected javax.swing.JCheckBox box_Birth_Certificate;
    protected javax.swing.JCheckBox box_Child_SNILS;
    protected javax.swing.JComboBox<String> box_Class;
    protected javax.swing.JCheckBox box_Contract;
    protected javax.swing.JComboBox<String> box_Date_Born;
    protected javax.swing.JComboBox<String> box_Date_Enrolment;
    protected javax.swing.JCheckBox box_Father_Consent;
    protected javax.swing.JCheckBox box_Father_Passport;
    protected javax.swing.JCheckBox box_Father_SNILS;
    protected javax.swing.JComboBox<String> box_First;
    protected javax.swing.JComboBox<String> box_Gender;
    protected javax.swing.JComboBox<String> box_Hours;
    protected javax.swing.JCheckBox box_Medical_Certificate;
    protected javax.swing.JComboBox<String> box_Month_Born;
    protected javax.swing.JComboBox<String> box_Month_Enrolment;
    protected javax.swing.JCheckBox box_Mother_Consent;
    protected javax.swing.JCheckBox box_Mother_Passport;
    protected javax.swing.JCheckBox box_Mother_SNILS;
    protected javax.swing.JCheckBox box_Photo;
    protected javax.swing.JComboBox<String> box_Program;
    protected javax.swing.JComboBox<String> box_School;
    protected javax.swing.JComboBox<String> box_School_Class;
    protected javax.swing.JComboBox<String> box_School_Class_Letter;
    protected javax.swing.JComboBox<String> box_School_Number;
    protected javax.swing.JComboBox<String> box_Second;
    protected javax.swing.JCheckBox box_Statement;
    protected javax.swing.JComboBox<String> box_Third;
    protected javax.swing.JComboBox<String> box_Year_Born;
    protected javax.swing.JComboBox<String> box_Year_Enrolment;
    protected javax.swing.JButton button_Cancel;
    protected javax.swing.JButton button_OK;
    protected javax.swing.JTextField field_Choir_Teacher;
    protected javax.swing.JTextField field_Ensemble_Teacher;
    protected javax.swing.JTextField field_Father_First_Name;
    protected javax.swing.JTextField field_Father_Last_Name;
    protected javax.swing.JTextField field_Father_Patronymic;
    protected javax.swing.JTextField field_Father_Phone;
    protected javax.swing.JTextField field_Father_Post;
    protected javax.swing.JTextField field_First_Name;
    protected javax.swing.JTextField field_Instrument;
    protected javax.swing.JTextField field_Last_Name;
    protected javax.swing.JTextField field_Mother_First_Name;
    protected javax.swing.JTextField field_Mother_Last_Name;
    protected javax.swing.JTextField field_Mother_Patronymic;
    protected javax.swing.JTextField field_Mother_Phone;
    protected javax.swing.JTextField field_Mother_Post;
    protected javax.swing.JTextField field_Patronymic_Name;
    protected javax.swing.JTextField field_Phone;
    protected javax.swing.JTextField field_Piano_Teacher;
    protected javax.swing.JTextField field_Spec_Teacher;
    protected javax.swing.JTextField field_Speciality;
    protected javax.swing.JTextField field_Theor_Teacher;
    private javax.swing.JLabel label_1_Semester;
    private javax.swing.JLabel label_2_Semester;
    private javax.swing.JLabel label_Adress;
    private javax.swing.JLabel label_Choir_Teacher;
    private javax.swing.JLabel label_Date_Born;
    private javax.swing.JLabel label_Date_Enrolment;
    private javax.swing.JLabel label_Ensemble_Teacher;
    private javax.swing.JLabel label_Father_First_Name;
    private javax.swing.JLabel label_Father_Last_Name;
    private javax.swing.JLabel label_Father_Patronymic_Name;
    private javax.swing.JLabel label_Father_Phone;
    private javax.swing.JLabel label_Father_Post;
    private javax.swing.JLabel label_Father_Work;
    private javax.swing.JLabel label_First_Name;
    private javax.swing.JLabel label_Gender;
    private javax.swing.JLabel label_Hours;
    private javax.swing.JLabel label_Instrument;
    private javax.swing.JLabel label_Klass;
    private javax.swing.JLabel label_Last_Name;
    private javax.swing.JLabel label_Mother_First_Name;
    private javax.swing.JLabel label_Mother_Last_Name;
    private javax.swing.JLabel label_Mother_Patronymic_Name;
    private javax.swing.JLabel label_Mother_Phone;
    private javax.swing.JLabel label_Mother_Post;
    private javax.swing.JLabel label_Mother_Work;
    private javax.swing.JLabel label_Patronymic_Name;
    private javax.swing.JLabel label_Phone;
    private javax.swing.JLabel label_Piano_Teacher;
    private javax.swing.JLabel label_Program;
    private javax.swing.JLabel label_Schedule;
    private javax.swing.JLabel label_School;
    private javax.swing.JLabel label_School_Class;
    private javax.swing.JLabel label_School_Number;
    private javax.swing.JLabel label_Spec_Teacher;
    private javax.swing.JLabel label_Specialty;
    private javax.swing.JLabel label_Theor_Teacher;
    private javax.swing.JPanel panel_1_Semester;
    private javax.swing.JPanel panel_2_Semester;
    private javax.swing.JPanel panel_Doc_Child;
    private javax.swing.JPanel panel_Doc_Father;
    private javax.swing.JPanel panel_Doc_Mother;
    private javax.swing.JPanel panel_Father;
    private javax.swing.JPanel panel_Mother;
    private javax.swing.JPanel panel_Notes2;
    private javax.swing.JPanel panel_Program;
    private javax.swing.JPanel panel_Pupil_Left;
    private javax.swing.JPanel panel_Pupil_Right;
    private javax.swing.JPanel panel_Teaching;
    private javax.swing.JScrollPane scroll_Pane_1_Semester;
    private javax.swing.JScrollPane scroll_Pane_2_Semester;
    private javax.swing.JScrollPane scroll_Pane_Achievment;
    private javax.swing.JScrollPane scroll_Pane_Adress;
    private javax.swing.JScrollPane scroll_Pane_Father_Work;
    private javax.swing.JScrollPane scroll_Pane_Mother_Work;
    private javax.swing.JScrollPane scroll_Pane_Notes;
    protected javax.swing.JTable table_Achievment;
    // End of variables declaration//GEN-END:variables
}
