/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pupilbase.mainframe;

import base.ListSorter;
import base.Pupil;
import presentations.ListAgeSorted;
import presentations.ListStart;
import presentations.ListSubjectSorted;
import sets.DaysSet;
import sets.YearsSet;

import javax.swing.*;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author Nobilis
 */          
public class SortSetting extends javax.swing.JFrame {
    private final static String[] DAYS = DaysSet.getDays();//{" ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"};
    private final static String[] BOX_CRITERION = {"", "Алфавит", "Возраст", "Расписание", "Программа", 
        "Класс", "Специальность", "Часы", "Преподаватель"};
    private final static String[] ALPHABET_ORDER = {"от А до Я", "от Я до А"};
    private final static String[] AGE_ORDER = {"возрастание (тек. дата)", "убывание (тек. дата)", 
        "возрастание (др. дата)", "убывание (др. дата)"};
    private final static String[] SCHEDULE_ORDER = {"понедельник", "вторник", "среда", 
        "четверг", "пятница", "суббота", "воскресенье"};
    private String[] CLASS_ORDER = {"возрастание", "убывание"};
    private String[] TEACHER_ORDER = {"специальность", "теория", "хор"};
    private String[] MONTHS = {" ", "январь", "февраль", "март", "апрель", "май", "июнь", "июль", "август", "сентябрь", "октябрь", "ноябрь", "декабрь"};
    private ArrayList<Pupil> base;
    private ArrayList<Pupil> removedBase;
    private File file;
    int[] levels = new int[5];
    private String Date="";
    private int visibleCriterion = 0;//Количество видимых JComboBox<> (0 => 1 элемент)
    private String[] boxOrder = {""};
    private String[] Years = YearsSet.getSet(10);
    private String ErrorMessage;
    /**
     * Creates new form SortSetting
     */
    public SortSetting(File file, ArrayList base, ArrayList removedBase) {
        initComponents();
        this.base = base;
        this.removedBase = removedBase;
        this.file = file;
        setBoxesVisible();
    }

    private SortSetting() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void setBoxesVisible() {
        criterionComboBox1.setVisible(false);
        criterionComboBox2.setVisible(false);
        criterionComboBox3.setVisible(false);
        criterionComboBox4.setVisible(false);
        settingComboBox0.setVisible(false);
        settingComboBox1.setVisible(false);
        settingComboBox2.setVisible(false);
        settingComboBox3.setVisible(false);
        settingComboBox4.setVisible(false);
        BoxYear0.setVisible(false);
        BoxMonth0.setVisible(false);
        BoxDay0.setVisible(false);
        BoxYear1.setVisible(false);
        BoxMonth1.setVisible(false);
        BoxDay1.setVisible(false);
        BoxYear2.setVisible(false);
        BoxMonth2.setVisible(false);
        BoxDay2.setVisible(false);
        BoxYear3.setVisible(false);
        BoxMonth3.setVisible(false);
        BoxDay3.setVisible(false);
        BoxYear4.setVisible(false);
        BoxMonth4.setVisible(false);
        BoxDay4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        addLevel = new javax.swing.JButton();
        removeLevel = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        criterionPanel = new javax.swing.JPanel();
        criterionLabel = new javax.swing.JLabel();
        criterionComboBox0 = new javax.swing.JComboBox<>();
        criterionComboBox1 = new javax.swing.JComboBox<>();
        criterionComboBox2 = new javax.swing.JComboBox<>();
        criterionComboBox3 = new javax.swing.JComboBox<>();
        criterionComboBox4 = new javax.swing.JComboBox<>();
        settingsLabel = new javax.swing.JLabel();
        settingComboBox0 = new javax.swing.JComboBox<>();
        settingComboBox1 = new javax.swing.JComboBox<>();
        settingComboBox2 = new javax.swing.JComboBox<>();
        settingComboBox3 = new javax.swing.JComboBox<>();
        settingComboBox4 = new javax.swing.JComboBox<>();
        BoxMonth0 = new javax.swing.JComboBox<>();
        BoxDay0 = new javax.swing.JComboBox<>();
        BoxYear0 = new javax.swing.JComboBox<>();
        dateLabel = new javax.swing.JLabel();
        BoxYear1 = new javax.swing.JComboBox<>();
        BoxMonth1 = new javax.swing.JComboBox<>();
        BoxDay1 = new javax.swing.JComboBox<>();
        BoxYear2 = new javax.swing.JComboBox<>();
        BoxMonth2 = new javax.swing.JComboBox<>();
        BoxDay2 = new javax.swing.JComboBox<>();
        BoxYear3 = new javax.swing.JComboBox<>();
        BoxMonth3 = new javax.swing.JComboBox<>();
        BoxDay3 = new javax.swing.JComboBox<>();
        BoxYear4 = new javax.swing.JComboBox<>();
        BoxMonth4 = new javax.swing.JComboBox<>();
        BoxDay4 = new javax.swing.JComboBox<>();
        
        okPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        
        criterionComboBox0.setFont(new java.awt.Font("Tahoma", 1, 16));
        criterionComboBox1.setFont(new java.awt.Font("Tahoma", 1, 16));
        criterionComboBox2.setFont(new java.awt.Font("Tahoma", 1, 16));
        criterionComboBox3.setFont(new java.awt.Font("Tahoma", 1, 16));
        criterionComboBox4.setFont(new java.awt.Font("Tahoma", 1, 16));
        settingsLabel.setFont(new java.awt.Font("Tahoma", 1, 16));
        settingComboBox0.setFont(new java.awt.Font("Tahoma", 1, 16));
        settingComboBox1.setFont(new java.awt.Font("Tahoma", 1, 16));
        settingComboBox2.setFont(new java.awt.Font("Tahoma", 1, 16));
        settingComboBox3.setFont(new java.awt.Font("Tahoma", 1, 16));
        settingComboBox4.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxMonth0.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxDay0.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxYear0.setFont(new java.awt.Font("Tahoma", 1, 16));
        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxYear1.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxMonth1.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxDay1.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxYear2.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxMonth2.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxDay2.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxYear3.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxMonth3.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxDay3.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxYear4.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxMonth4.setFont(new java.awt.Font("Tahoma", 1, 16));
        BoxDay4.setFont(new java.awt.Font("Tahoma", 1, 16));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
       
        addLevel.setText("Добавить уровень");
        addLevel.setFont(new java.awt.Font("Tahoma", 1, 16));
        addLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLevelActionPerformed(evt);
            }
        });

        removeLevel.setText("Удалить уровень");
        removeLevel.setFont(new java.awt.Font("Tahoma", 1, 16));
        removeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLevelActionPerformed(evt);
            }
        });

        resetButton.setText("Сброс");
        resetButton.setFont(new java.awt.Font("Tahoma", 1, 16));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
                
        
        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(addLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(addLevel)
                .addComponent(removeLevel)
                .addComponent(resetButton))
        );

        criterionLabel.setFont(new java.awt.Font("Tahoma", 1, 16));
        criterionLabel.setText("   Критерии");

        criterionComboBox0.setModel(new javax.swing.DefaultComboBoxModel<>(BOX_CRITERION));
        criterionComboBox0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterionComboBox0ActionPerformed(evt);
            }
        });

        criterionComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(BOX_CRITERION));
        criterionComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterionComboBox1ActionPerformed(evt);
            }
        });

        criterionComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(BOX_CRITERION));
        criterionComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterionComboBox2ActionPerformed(evt);
            }
        });

        criterionComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(BOX_CRITERION));
        criterionComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterionComboBox3ActionPerformed(evt);
            }
        });
        
        criterionComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(BOX_CRITERION));
        criterionComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterionComboBox4ActionPerformed(evt);
            }
        });        

        settingsLabel.setText("   Настройки");



        settingComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(boxOrder));
        settingComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingComboBox1ActionPerformed(evt);
            }
        });

        settingComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(boxOrder));
        settingComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingComboBox2ActionPerformed(evt);
            }
        });

        settingComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(boxOrder));
        settingComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingComboBox3ActionPerformed(evt);
            }
        });

        settingComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(boxOrder));
        settingComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingComboBox4ActionPerformed(evt);
            }
        });

        BoxMonth0.setModel(new javax.swing.DefaultComboBoxModel<>(MONTHS));
        BoxMonth0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxMonth0ActionPerformed(evt);
            }
        });

        BoxDay0.setModel(new javax.swing.DefaultComboBoxModel<>(DAYS));
        BoxDay0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxDay0ActionPerformed(evt);
            }
        });

        BoxYear0.setModel(new javax.swing.DefaultComboBoxModel<>(Years));
        BoxYear0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxYear0ActionPerformed(evt);
            }
        });

        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 16));
        dateLabel.setText("   Дата");

        BoxYear1.setModel(new javax.swing.DefaultComboBoxModel<>(Years));
        BoxYear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxYear1ActionPerformed(evt);
            }
        });

        BoxMonth1.setModel(new javax.swing.DefaultComboBoxModel<>(MONTHS));
        BoxMonth1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxMonth1ActionPerformed(evt);
            }
        });

        BoxDay1.setModel(new javax.swing.DefaultComboBoxModel<>(DAYS));
        BoxDay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxDay1ActionPerformed(evt);
            }
        });

        BoxYear2.setModel(new javax.swing.DefaultComboBoxModel<>(Years));
        BoxYear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxYear2ActionPerformed(evt);
            }
        });

        BoxMonth2.setModel(new javax.swing.DefaultComboBoxModel<>(MONTHS));
        BoxMonth2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxMonth2ActionPerformed(evt);
            }
        });

        BoxDay2.setModel(new javax.swing.DefaultComboBoxModel<>(DAYS));
        BoxDay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxDay2ActionPerformed(evt);
            }
        });

        BoxYear3.setModel(new javax.swing.DefaultComboBoxModel<>(Years));
        BoxYear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxYear3ActionPerformed(evt);
            }
        });

        BoxMonth3.setModel(new javax.swing.DefaultComboBoxModel<>(MONTHS));
        BoxMonth3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxMonth3ActionPerformed(evt);
            }
        });

        BoxDay3.setModel(new javax.swing.DefaultComboBoxModel<>(DAYS));
        BoxDay3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxDay3ActionPerformed(evt);
            }
        });

        BoxYear4.setModel(new javax.swing.DefaultComboBoxModel<>(Years));
        BoxYear4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxYear4ActionPerformed(evt);
            }
        });

        BoxMonth4.setModel(new javax.swing.DefaultComboBoxModel<>(MONTHS));
        BoxMonth4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxMonth4ActionPerformed(evt);
            }
        });

        BoxDay4.setModel(new javax.swing.DefaultComboBoxModel<>(DAYS));
        BoxDay4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxDay4ActionPerformed(evt);
            }
        });

        criterionComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(BOX_CRITERION));
        criterionComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criterionComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout criterionPanelLayout = new javax.swing.GroupLayout(criterionPanel);
        criterionPanel.setLayout(criterionPanelLayout);
        criterionPanelLayout.setHorizontalGroup(
            criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criterionPanelLayout.createSequentialGroup()
                .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(criterionComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(criterionComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(criterionComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(criterionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(criterionComboBox0, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(criterionComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(settingComboBox0, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(criterionPanelLayout.createSequentialGroup()
                                    .addComponent(BoxYear0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BoxMonth0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BoxDay0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(criterionPanelLayout.createSequentialGroup()
                                .addComponent(BoxYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BoxMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BoxDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, criterionPanelLayout.createSequentialGroup()
                                .addComponent(BoxYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BoxMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BoxDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, criterionPanelLayout.createSequentialGroup()
                            .addComponent(BoxYear3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BoxMonth3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BoxDay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, criterionPanelLayout.createSequentialGroup()
                        .addComponent(BoxYear4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BoxMonth4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BoxDay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        criterionPanelLayout.setVerticalGroup(
            criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criterionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterionLabel)
                    .addComponent(settingsLabel)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BoxYear0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoxMonth0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoxDay0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(criterionComboBox0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(settingComboBox0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BoxYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoxMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoxDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(settingComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(criterionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BoxYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoxMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoxDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(criterionComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(settingComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BoxYear3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoxMonth3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoxDay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(criterionComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(settingComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BoxYear4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoxMonth4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoxDay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(criterionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(criterionComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(settingComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        
        
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 16));
        cancelButton.setText("Отмена");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setFont(new java.awt.Font("Tahoma", 1, 16));
        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout okPanelLayout = new javax.swing.GroupLayout(okPanel);
        okPanel.setLayout(okPanelLayout);
        okPanelLayout.setHorizontalGroup(
            okPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, okPanelLayout.createSequentialGroup()
                .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        okPanelLayout.setVerticalGroup(
            okPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(okPanelLayout.createSequentialGroup()
                .addGroup(okPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(criterionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(okPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criterionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(okPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void BoxYear0ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void BoxYear1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void BoxYear2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void BoxYear3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void BoxYear4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
    
    //Добавление уровней сортировки
    private void addLevelActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(visibleCriterion<4)visibleCriterion++;
        visibleComponent();
    }                                        
    
    //Удаление уровней сортировки
    private void removeLevelActionPerformed(java.awt.event.ActionEvent evt) {                                            
        if(visibleCriterion>0)
            {
            levels[visibleCriterion]=0;
            visibleCriterion--;
            }
        visibleComponent();
    }  
    
    //Отмена настроек
    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        visibleCriterion=4;
        visibleComponent();
        criterionComboBox0.setSelectedIndex(2);
        criterionComboBox1.setSelectedIndex(2);
        criterionComboBox2.setSelectedIndex(2);
        criterionComboBox3.setSelectedIndex(2);
        criterionComboBox4.setSelectedIndex(2);
        settingComboBox0.setSelectedIndex(3);
        settingComboBox1.setSelectedIndex(3);
        settingComboBox2.setSelectedIndex(3);
        settingComboBox3.setSelectedIndex(3);
        settingComboBox4.setSelectedIndex(3);
        BoxDay4.setSelectedIndex(0);
        BoxMonth4.setSelectedIndex(0);
        BoxYear4.setSelectedIndex(0);
        BoxDay3.setSelectedIndex(0);
        BoxMonth3.setSelectedIndex(0);
        BoxYear3.setSelectedIndex(0);
        BoxDay2.setSelectedIndex(0);
        BoxMonth2.setSelectedIndex(0);
        BoxYear2.setSelectedIndex(0);
        BoxDay1.setSelectedIndex(0);
        BoxMonth1.setSelectedIndex(0);
        BoxYear1.setSelectedIndex(0);
        BoxDay0.setSelectedIndex(0);
        BoxMonth0.setSelectedIndex(0);
        BoxYear0.setSelectedIndex(0);
        settingComboBox4.setSelectedIndex(0);
        settingComboBox3.setSelectedIndex(0);
        settingComboBox2.setSelectedIndex(0);
        settingComboBox1.setSelectedIndex(0);
        settingComboBox0.setSelectedIndex(0);
        criterionComboBox4.setSelectedIndex(0);
        criterionComboBox3.setSelectedIndex(0);
        criterionComboBox2.setSelectedIndex(0);
        criterionComboBox1.setSelectedIndex(0);
        criterionComboBox0.setSelectedIndex(0);
        visibleCriterion=0;
        visibleComponent();
    }
    
    /*
    Сохранение критериев сортировки в массив levels. Если уровень не активен, 
    в массив записывается 0.
    */
    private void criterionComboBox0ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        levels[0] = criterionComboBox0.getSelectedIndex();
        visibleSetting(levels[0], settingComboBox0);
        visibleDate(levels[0], settingComboBox0.getSelectedIndex(), BoxYear0, BoxMonth0, BoxDay0);
        settingComboBox0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            settingComboBox0ActionPerformed(evt);
            }
        });
    }                                                  

    private void criterionComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        levels[1] = criterionComboBox1.getSelectedIndex();
        visibleSetting(levels[1], settingComboBox1);
        visibleDate(levels[1], settingComboBox1.getSelectedIndex(), BoxYear1, BoxMonth1, BoxDay1);
        settingComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            settingComboBox1ActionPerformed(evt);
            }
        });
    }

    private void criterionComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        levels[2] = criterionComboBox2.getSelectedIndex();
        visibleSetting(levels[2], settingComboBox2);
        visibleDate(levels[2], settingComboBox2.getSelectedIndex(), BoxYear2, BoxMonth2, BoxDay2);
        settingComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            settingComboBox2ActionPerformed(evt);
            }
        });
    }                                                  

    private void criterionComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        levels[3] = criterionComboBox3.getSelectedIndex();
        visibleSetting(levels[3], settingComboBox3);
        visibleDate(levels[3], settingComboBox3.getSelectedIndex(), BoxYear3, BoxMonth3, BoxDay3);
        settingComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            settingComboBox3ActionPerformed(evt);
            }
        });
    }                                                  

    private void criterionComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        levels[4] = criterionComboBox4.getSelectedIndex();
        visibleSetting(levels[4], settingComboBox4);
        visibleDate(levels[4], settingComboBox4.getSelectedIndex(), BoxYear4, BoxMonth4, BoxDay4);
        settingComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            settingComboBox4ActionPerformed(evt);
            }
        });
    }                                                  
    /*
    Настройка видимости/невидимости даты.
    */
    private void settingComboBox0ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        if(levels[0]==2&(settingComboBox0.getSelectedIndex()==2
                |settingComboBox0.getSelectedIndex()==3)){
            BoxYear0.setVisible(true);
            BoxMonth0.setVisible(true);
            BoxDay0.setVisible(true);
        }else{
            BoxYear0.setVisible(false);
            BoxMonth0.setVisible(false);
            BoxDay0.setVisible(false);
        }
    }                                                

    private void settingComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        if(levels[1]==2&(settingComboBox1.getSelectedIndex()==2
                |settingComboBox1.getSelectedIndex()==3)){
            BoxYear1.setVisible(true);
            BoxMonth1.setVisible(true);
            BoxDay1.setVisible(true);
        }else{
            BoxYear1.setVisible(false);
            BoxMonth1.setVisible(false);
            BoxDay1.setVisible(false);
        }
    }                         

    private void settingComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        if(levels[2]==2&(settingComboBox2.getSelectedIndex()==2
                |settingComboBox2.getSelectedIndex()==3)){
            BoxYear2.setVisible(true);
            BoxMonth2.setVisible(true);
            BoxDay2.setVisible(true);
        }else{
            BoxYear2.setVisible(false);
            BoxMonth2.setVisible(false);
            BoxDay2.setVisible(false);
        }
    }                                            

    private void settingComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        if(levels[3]==2&(settingComboBox3.getSelectedIndex()==2
                |settingComboBox3.getSelectedIndex()==3)){
            BoxYear3.setVisible(true);
            BoxMonth3.setVisible(true);
            BoxDay3.setVisible(true);
        }else{
            BoxYear3.setVisible(false);
            BoxMonth3.setVisible(false);
            BoxDay3.setVisible(false);
        }
    }

    private void settingComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        if(levels[4]==2&(settingComboBox4.getSelectedIndex()==2
                |settingComboBox4.getSelectedIndex()==3)){
            BoxYear4.setVisible(true);
            BoxMonth4.setVisible(true);
            BoxDay4.setVisible(true);
        }else{
            BoxYear4.setVisible(false);
            BoxMonth4.setVisible(false);
            BoxDay4.setVisible(false);
        }
    }               

    private void BoxMonth0ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void BoxMonth1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void BoxMonth2ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void BoxMonth3ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void BoxMonth4ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void BoxDay0ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void BoxDay1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void BoxDay2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void BoxDay3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void BoxDay4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (checkLevels()==true&&checkDate()==true){
            int [] settings = {settingComboBox0.getSelectedIndex(), 
            settingComboBox1.getSelectedIndex(), 
            settingComboBox2.getSelectedIndex(), 
            settingComboBox3.getSelectedIndex(),
            settingComboBox4.getSelectedIndex()};
            new ListSorter(base, levels, settings, Date);
            int selectFrame=0;
            int selectSubject=0;
            for(int i=0; i<levels.length; i++){
                if(levels[i]==8){
                    selectFrame++;
                    selectSubject=settings[i];}
            }
            if(selectFrame!=0){
                ListSubjectSorted list = new ListSubjectSorted(file,base, removedBase, Date, selectSubject);
                list.setBounds(0, 100, 1280, 672);
                list.setVisible(true);
                this.dispose();
            }
            else{
                ListAgeSorted list = new ListAgeSorted(file,base, removedBase, Date);
                list.setBounds(160, 100, 960, 672);
                list.setVisible(true);
                this.dispose();    }
        }
    }    
    
    //Повторный вызов класса ListStart с внесенными ранее изменениями. 
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        ListStart list = new ListStart(file, base, removedBase);
        list.setBounds(215, 100, 850, 672);
        list.setVisible(true);
        this.dispose();
    }                                            
    
    //Настройка видимости компонентов
    private void visibleComponent(){
        criterionComboBox1.setVisible(visibleCriterion>0);
        criterionComboBox2.setVisible(visibleCriterion>1);
        criterionComboBox3.setVisible(visibleCriterion>2);
        criterionComboBox4.setVisible(visibleCriterion>3);
        settingComboBox1.setVisible(visibleCriterion>0&(levels[1]==1|
                levels[1]==2|levels[1]==3|levels[1]==5|levels[1]==8));
        settingComboBox2.setVisible(visibleCriterion>1&(levels[2]==1|
                levels[2]==2|levels[2]==3|levels[2]==5|levels[2]==8));
        settingComboBox3.setVisible(visibleCriterion>2&(levels[3]==1|
                levels[3]==2|levels[3]==3|levels[3]==5|levels[3]==8));
        settingComboBox4.setVisible(visibleCriterion>3&(levels[4]==1|
                levels[4]==2|levels[4]==3|levels[4]==5|levels[4]==8));
        BoxYear1.setVisible(visibleCriterion>0&levels[1]==2
                &(settingComboBox1.getSelectedIndex()==2|
                        settingComboBox1.getSelectedIndex()==3));
        BoxMonth1.setVisible(visibleCriterion>0&levels[1]==2
                &(settingComboBox1.getSelectedIndex()==2|
                        settingComboBox1.getSelectedIndex()==3));
        BoxDay1.setVisible(visibleCriterion>0&levels[1]==2
                &(settingComboBox1.getSelectedIndex()==2|
                        settingComboBox1.getSelectedIndex()==3));
        BoxYear2.setVisible(visibleCriterion>1&levels[2]==2
                &(settingComboBox2.getSelectedIndex()==2|
                        settingComboBox2.getSelectedIndex()==3));
        BoxMonth2.setVisible(visibleCriterion>1&levels[2]==2
                &(settingComboBox2.getSelectedIndex()==2|
                        settingComboBox2.getSelectedIndex()==3));
        BoxDay2.setVisible(visibleCriterion>1&levels[2]==2
                &(settingComboBox2.getSelectedIndex()==2|
                        settingComboBox2.getSelectedIndex()==3));
        BoxYear3.setVisible(visibleCriterion>2&levels[3]==2
                &(settingComboBox3.getSelectedIndex()==2|
                        settingComboBox3.getSelectedIndex()==3));
        BoxMonth3.setVisible(visibleCriterion>2&levels[3]==2
                &(settingComboBox3.getSelectedIndex()==2|
                        settingComboBox3.getSelectedIndex()==3));
        BoxDay3.setVisible(visibleCriterion>2&levels[3]==2
                &(settingComboBox3.getSelectedIndex()==2|
                        settingComboBox3.getSelectedIndex()==3));
        BoxYear4.setVisible(visibleCriterion>3&levels[4]==2
                &(settingComboBox4.getSelectedIndex()==2|
                        settingComboBox4.getSelectedIndex()==3));
        BoxMonth4.setVisible(visibleCriterion>3&levels[4]==2
                &(settingComboBox4.getSelectedIndex()==2|
                        settingComboBox4.getSelectedIndex()==3));
        BoxDay4.setVisible(visibleCriterion>3&levels[4]==2
                &(settingComboBox4.getSelectedIndex()==2|
                        settingComboBox4.getSelectedIndex()==3));       
    }
    
    //
    private void visibleSetting(int lev, javax.swing.JComboBox order){
        order.setVisible(lev==1|lev==2|lev==3|lev==5|lev==8);
        switch (lev) {
            case 1:
                order.setModel(new javax.swing.DefaultComboBoxModel<>(ALPHABET_ORDER));
                break;
            case 2:
                order.setModel(new javax.swing.DefaultComboBoxModel<>(AGE_ORDER));
                break;
            case 3:
                order.setModel(new javax.swing.DefaultComboBoxModel<>(SCHEDULE_ORDER));
                break;
            case 5:
                order.setModel(new javax.swing.DefaultComboBoxModel<>(CLASS_ORDER));
                break;
            case 8:
                order.setModel(new javax.swing.DefaultComboBoxModel<>(TEACHER_ORDER));
                break;    
            default:
                order.setModel(new javax.swing.DefaultComboBoxModel<>(boxOrder));
                break;
        }
    }
    
    private void visibleDate(int vis, int ind, javax.swing.JComboBox year, 
        javax.swing.JComboBox month, javax.swing.JComboBox date){
            year.setVisible(vis==2&(ind==3|ind==4));
            month.setVisible(vis==2&(ind==3|ind==4));
            date.setVisible(vis==2&(ind==3|ind==4));
    }
    
    private void getDate(javax.swing.JComboBox<String> year, 
            javax.swing.JComboBox<String> month, 
            javax.swing.JComboBox<String> day){
        
        switch(month.getSelectedIndex()){
        case 1: Date = "01";break;
        case 2: Date = "02";break;
        case 3: Date = "03";break;
        case 4: Date = "04";break;
        case 5: Date = "05";break;
        case 6: Date = "06";break;
        case 7: Date = "07";break;
        case 8: Date = "08";break;
        case 9: Date = "09";break;
        case 10: Date = "10";break;
        case 11: Date = "11";break;
        case 12: Date = "12";break;
        default: Date = "  ";break;
        }
        Date = year.getSelectedItem()+"-"+Date+"-"+ day.getSelectedItem();
    }
//Проверка на ошибки полей сортировки    
    private boolean checkLevels(){
        int error = 0;
        if(levels[0]==0){
            error++;
            ErrorMessage = "Уровень " + 1 + " пустой";
            createDialog("Ошибка", true);
        }
        else if(visibleCriterion!=0){
            for(int l=0;l<visibleCriterion;l++){
                for(int m=l+1;m<visibleCriterion+1;m++){
                    if(levels[m]==0){
                        error++;
                        ErrorMessage = "Уровень " + (m+1) + " пустой";
                        createDialog("Ошибка", true);                        
                    }
                    else if(levels[l]==levels[m]){
                        error++;
                        ErrorMessage = "Уровень " + (m+1) 
                            + " дублирует уровень " + (l+1);
                        createDialog("Ошибка", true);
                    }
                    if(error!=0)break;
                }
                if(error!=0)break;
            }
        }
        return error==0;
    }
    
    private boolean checkDate(){
        int error = 0;
        if(criterionComboBox0.getSelectedIndex()==2
            &&(settingComboBox0.getSelectedIndex()==2
            ||settingComboBox0.getSelectedIndex()==3))
            {if(BoxYear0.getSelectedIndex()==0|BoxMonth0.getSelectedIndex()==0
                |BoxDay0.getSelectedIndex()==0)error++;
            else if (!checkDate2(BoxYear0, BoxMonth0, BoxDay0))error++;
            else getDate(BoxYear0, BoxMonth0, BoxDay0);
        }
        else if(criterionComboBox1.getSelectedIndex()==2
            &&(visibleCriterion>0&&(settingComboBox1.getSelectedIndex()==2
            ||settingComboBox1.getSelectedIndex()==3)))
            {if(BoxYear1.getSelectedIndex()==0|BoxMonth1.getSelectedIndex()==0
                |BoxDay1.getSelectedIndex()==0)error++;
            else if (!checkDate2(BoxYear1, BoxMonth1, BoxDay1))error++;
            else getDate(BoxYear1, BoxMonth1, BoxDay1);
        }
        else if(criterionComboBox2.getSelectedIndex()==2
            &&(visibleCriterion>1&&(settingComboBox2.getSelectedIndex()==2
            ||settingComboBox2.getSelectedIndex()==3)))
            {if(BoxYear2.getSelectedIndex()==0|BoxMonth2.getSelectedIndex()==0
                |BoxDay2.getSelectedIndex()==0)error++;
            else if (!checkDate2(BoxYear2, BoxMonth2, BoxDay2))error++;
            else getDate(BoxYear2, BoxMonth2, BoxDay2);
        }
        else if(criterionComboBox3.getSelectedIndex()==2
            &&(visibleCriterion>2&&(settingComboBox3.getSelectedIndex()==2
            ||settingComboBox3.getSelectedIndex()==3)))
            {if(BoxYear3.getSelectedIndex()==0|BoxMonth3.getSelectedIndex()==0
                |BoxDay3.getSelectedIndex()==0)error++;
            else if (!checkDate2(BoxYear3, BoxMonth3, BoxDay3))error++;
            else getDate(BoxYear3, BoxMonth3, BoxDay3);
        }
        else if(criterionComboBox4.getSelectedIndex()==2
            &&(visibleCriterion>3&&(settingComboBox4.getSelectedIndex()==2
            ||settingComboBox4.getSelectedIndex()==3)))
            {if(BoxYear4.getSelectedIndex()==0|BoxMonth4.getSelectedIndex()==0
                |BoxDay4.getSelectedIndex()==0)error++;
            else if (!checkDate2(BoxYear4, BoxMonth4, BoxDay4))error++;
            else getDate(BoxYear4, BoxMonth4, BoxDay4);
        }else{
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date currentDate = new Date();
            Date = df.format(currentDate);}
        if(error!=0){
            ErrorMessage = "Неправильная дата";
            createDialog("Ошибка", true);
        }
        return error==0;
    }
    
    private boolean checkDate2(javax.swing.JComboBox<String> year, 
            javax.swing.JComboBox<String> month, 
            javax.swing.JComboBox<String> day){
        int error = 0;
        if(month.getSelectedIndex()==4|month.getSelectedIndex()==6
                |month.getSelectedIndex()==9|month.getSelectedIndex()==11){
            if(day.getSelectedIndex()==31)error++;
        }
        else if(month.getSelectedIndex()==2){
            if(day.getSelectedIndex()>29)error++;
            else if(day.getSelectedIndex()>28&year.getSelectedIndex()%4!=0)error++;
        }
        return error==0;
    }
    
    private JDialog createDialog(String title, boolean modal)
    {
        JDialog dialog = new JDialog(this, title, modal);
        dialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dialog.setBounds(460, 467, 360, 90);
        javax.swing.JLabel label = new javax.swing.JLabel();
        dialog.add(label);
        label.setFont(new java.awt.Font("Tahoma", 1, 16));
        label.setText(ErrorMessage);
        dialog.setVisible(true);
        return dialog;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SortSetting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> BoxDay0;
    private javax.swing.JComboBox<String> BoxDay1;
    private javax.swing.JComboBox<String> BoxDay2;
    private javax.swing.JComboBox<String> BoxDay3;
    private javax.swing.JComboBox<String> BoxDay4;
    private javax.swing.JComboBox<String> BoxMonth0;
    private javax.swing.JComboBox<String> BoxMonth1;
    private javax.swing.JComboBox<String> BoxMonth2;
    private javax.swing.JComboBox<String> BoxMonth3;
    private javax.swing.JComboBox<String> BoxMonth4;
    private javax.swing.JComboBox<String> BoxYear0;
    private javax.swing.JComboBox<String> BoxYear1;
    private javax.swing.JComboBox<String> BoxYear2;
    private javax.swing.JComboBox<String> BoxYear3;
    private javax.swing.JComboBox<String> BoxYear4;
    private javax.swing.JButton addLevel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> criterionComboBox0;
    private javax.swing.JComboBox<String> criterionComboBox1;
    private javax.swing.JComboBox<String> criterionComboBox2;
    private javax.swing.JComboBox<String> criterionComboBox3;
    private javax.swing.JComboBox<String> criterionComboBox4;
    private javax.swing.JLabel criterionLabel;
    private javax.swing.JPanel criterionPanel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel okPanel;
    private javax.swing.JButton removeLevel;
    private javax.swing.JButton resetButton;
    private javax.swing.JComboBox<String> settingComboBox0;
    private javax.swing.JComboBox<String> settingComboBox1;
    private javax.swing.JComboBox<String> settingComboBox2;
    private javax.swing.JComboBox<String> settingComboBox3;
    private javax.swing.JComboBox<String> settingComboBox4;
    private javax.swing.JLabel settingsLabel;
    // End of variables declaration                   
}
